-- CreateEnum
CREATE TYPE "DeviceCategory" AS ENUM ('SMART_BULB', 'SMART_PANEL', 'SMART_PLUG', 'ENERGY_METER', 'CAMERA', 'SMART_LOCK', 'CONTACT_SENSOR', 'MOTION_SENSOR', 'THERMOSTAT', 'HVAC', 'SMART_SPEAKER', 'SMART_TV', 'APPLIANCE', 'ROUTER', 'OTHER');

-- AlterTable
ALTER TABLE "Device" ADD COLUMN     "category" "DeviceCategory",
ADD COLUMN     "room" TEXT;
