# =====================================================
# Identificadores del proyecto
# =====================================================
sonar.projectKey=TFG-eromero
sonar.projectName=TFG-eromero
sonar.sourceEncoding=UTF-8

# =====================================================
# Rutas de código fuente y tests (Separación vital)
# =====================================================
# Dónde está el código de negocio:
sonar.sources=services,infra,apps

# Dónde están los tests (Le decimos a Sonar que busque tests dentro de estas carpetas):
sonar.tests=services,apps

# Le enseñamos a Sonar a diferenciar qué es código y qué es test:
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,**/*.e2e-spec.ts

# =====================================================
# Exclusiones Globales (Lo que Sonar no debe ni mirar)
# =====================================================
sonar.exclusions=**/node_modules/**,**/dist/**,**/.nx/**,**/coverage/**,**/*.data.ts, **/*.mock.ts, **/*.spec.ts

# =====================================================
# Exclusiones de Cobertura (Lo que Sonar mira, pero NO evalúa su % de test)
# =====================================================
# Tiene que coincidir con tu jest.config.ts para que las matemáticas no fallen:
sonar.coverage.exclusions=**/*.module.ts,**/*.dto.ts,**/*.entity.ts,**/main.ts,**/prisma/**,**/*.config.ts,**/*.js, **/*.data.ts, **/*.mock.ts

# =====================================================
# Reporte de cobertura JavaScript/TypeScript
# =====================================================
# Usar comodines atados a las carpetas raíz es más rápido y seguro que un **/ global:
sonar.javascript.lcov.reportPaths=services/auth/coverage/lcov.info,services/iot-manager/coverage/lcov.info,apps/webapp/coverage/lcov.info

# Evita que el analizador JS/TS intente usar tsconfig secundarios incompatibles.
sonar.typescript.tsconfigPaths=apps/webapp/tsconfig.json,services/auth/tsconfig.json,services/iot-manager/tsconfig.json

# =====================================================
# Conexión al servidor
# =====================================================
sonar.host.url=http://seralu4.esi.uclm.es:1521