# Identificadores del proyecto en SonarQube (Tienen que coincidir exactamente con tu panel)
sonar.projectKey=TFG-eromero
sonar.projectName=TFG-eromero

# Le decimos a Sonar que analice tanto la carpeta de apps como la de services
sonar.sources=apps, services

# Excluimos carpetas que no queremos analizar (dependencias, configuraciones)
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/*.test.js

# URL de tu servidor de la universidad
sonar.host.url=http://seralu4.esi.uclm.es:1521

# El token lo pasaremos por consola, no se escribe aquí.