# Identificadores del proyecto en SonarQube (Tienen que coincidir exactamente con tu panel)
sonar.projectKey=TFG-eromero
sonar.projectName=TFG-eromero

# Rutas de código a analizar
sonar.sources=services,infra,apps

# Exclusiones recomendadas
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts

# Reporte de cobertura JavaScript/TypeScript
sonar.javascript.lcov.reportPaths=**/coverage/lcov.info

# URL de tu servidor de la universidad
sonar.host.url=http://seralu4.esi.uclm.es:1521

# El token lo pasaremos por consola, no se escribe aquí.

# Excluir archivos de arranque y módulos de la métrica de cobertura
sonar.coverage.exclusions=**/main.ts, **/*.module.ts, **/server.ts